name: happy_students
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  flutter: 3.19.2
  sdk: 3.3.4

dependencies:
  # https://pub.dev/packages/dio
  flutter:
    sdk: flutter
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  # https://pub.dev/packages/get_it
  get_it: ^7.6.7
  # https://pub.dev/packages/firebase_remote_config
  intl: any
  # https://pub.dev/packages/logger
  logger: ^2.1.0
  # https://pub.dev/packages/riverpod
  flutter_riverpod: ^2.5.1
  # https://pub.dev/packages/riverpod_annotation
  riverpod_annotation: ^2.3.5
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.2
  # https://pub.dev/packages/path_provider
  json_serializable: ^6.7.1
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.8.1
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.10+1
  # https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.3.9
  # https://pub.dev/packages/in_app_purchase
  in_app_purchase: ^3.1.13
  # https://pub.dev/packages/collection
  collection: ^1.18.0
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.2.6
  # https://pub.dev/packages/carousel_slider
  carousel_slider: ^4.2.1
  # https://pub.dev/packages/flutter_animate
  flutter_animate: ^4.5.0
  http: ^1.2.1

dev_dependencies:
  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1

  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.9
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/riverpod_generator
  riverpod_generator: ^2.3.11
  # https://pub.dev/packages/isar_generator


flutter_launcher_icons:
  ios: true
  android: false
  image_path: "assets/app_icon/icon.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/